=== kkzzhizhou/scoop-apps/bucket/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "A comment."
        },
        "_comment": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "identifier": {
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== kkzzhizhou/scoop-apps/bucket/php5.6.14.json
{
    "homepage": "https://windows.php.net/downloads/releases/archives",
    "version": "5.6.14",
    "license": {
        "identifier": "PHP-3.01",
        "url": "https://www.php.net/license/"
    },
    "architecture": {
        "64bit": {
            "url": "https://windows.php.net/downloads/releases/archives/php-5.6.14-Win32-VC11-x64.zip",
            "hash": "8ded94a696e4e8d20b93f121366b14f59b5a82127c048d1aba2c4fba3786f67e"
        },
        "32bit": {
            "url": "https://windows.php.net/downloads/releases/archives/php-5.6.14-Win32-VC11-x86.zip",
            "hash": "fc222df5dcdb137941498bb726045d78f67d2b1bd12df8adc8acd1d6c1869d13"
        }
    },
    "bin": [
        "php.exe",
        "php-cgi.exe"
    ],
    "persist": "conf.d",
    "env_set": {
        "PHP_INI_SCAN_DIR": "$persist_dir;$dir\\conf.d;"
    },
    "post_install": "if($bucket) { . \"$(Find-BucketDirectory $bucket\\bin\\postinstall.ps1)\" -dir \"$dir\" }",
    "suggest": {
        "vcredist": "extras/vcredist2012"
    }
}

=== kkzzhizhou/scoop-apps/bucket/winbtrfs.json
{
    "version": "1.8.2",
    "description": "BTRFS filesystem driver.",
    "homepage": "https://github.com/maharmstone/btrfs",
    "license": "LGPL-3.0-or-later",
    "notes": [
        "If you using Windows 10 and have Secure Boot enabled, you may have to make a registry change in order for the driver to be loaded.",
        "See https://github.com/maharmstone/btrfs#secureboot."
    ],
    "url": "https://github.com/maharmstone/btrfs/releases/download/v1.8.2/btrfs-1.8.2.zip",
    "hash": "5672da6ba0df205fc8b7732f5caf6594065ad6fad7726f8c029d7a6609f47771",
    "pre_install": "if (!$global) { Write-Host -Foreground Red \"$app should be installed globally.\"; break }",
    "installer": {
        "script": [
            "using namespace System.Security.Cryptography.X509Certificates",
            "# Add cert first before installing driver",
            "$cert = (Get-AuthenticodeSignature \"$dir/btrfs.cat\").SignerCertificate",
            "if (!(Get-ChildItem Cert:/CurrentUser/TrustedPublisher -Recurse | Where-Object { $_.Thumbprint -eq $cert.Thumbprint })) {",
            "    Write-Host 'Cert not found, adding to trusted store...'",
            "    $store = [X509Store]::new([StoreName]::TrustedPublisher, [StoreLocation]::LocalMachine)",
            "    $store.Open([OpenFlags]::ReadWrite)",
            "    $store.Add($cert.Export([X509ContentType]::Cert))",
            "    $store.Close()",
            "}",
            "",
            "Write-Host 'Installing driver...'",
            "Invoke-ExternalCommand pnputil -ArgumentList @('/add-driver', \"$dir/btrfs.inf\", '/install') -RunAs -ContinueExitCodes @{ 3010 = 'A system reboot is required to finalize the installation.' } | Out-Null"
        ]
    },
    "post_install": [
        "Set-ItemProperty HKLM:/SYSTEM/CurrentControlSet/Services/btrfs Compress 1",
        "Set-ItemProperty HKLM:/SYSTEM/CurrentControlSet/Services/btrfs CompressType 3"
    ],
    "uninstaller": {
        "script": [
            "if ($cmd -ne 'uninstall') { return }",
            "Invoke-ExternalCommand pnputil -ArgumentList @('/remove-device', 'ROOT\\btrfs\\0000') -RunAs -ContinueExitCodes @{ 3010 = 'A system reboot is required to finalize the uninstallation.' } | Out-Null",
            "pnputil /delete-driver \"$dir\\btrfs.inf\" /uninstall | Out-Null",
            "pnputil /delete-driver \"$dir\\btrfs-vol.inf\" /uninstall | Out-Null",
            "sc delete btrfs | Out-Null"
        ]
    },
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/maharmstone/btrfs/releases/download/v$version/btrfs-$version.zip"
    }
}

=== kkzzhizhou/scoop-apps/bucket/plebbit-cli.json
{
    "version": "0.11.37",
    "description": "An interface to Plebbit API through command line.",
    "homepage": "https://github.com/plebbit/plebbit-cli",
    "license": "GPL-2.0-only",
    "architecture": {
        "64bit": {
            "url": "https://github.com/plebbit/plebbit-cli/releases/download/v0.11.37/plebbit_installer_win32_x64.exe#/dl.7z",
            "hash": "7997183d07b3c05ffd7ce38ca11ea28e86d38a339076b86b5e78271ba1130e7d"
        }
    },
    "post_install": "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninstall*\" -Force -Recurse",
    "bin": [
        [
            "client\\bin\\node.exe",
            "plebbit",
            "$dir\\client\\bin\\run"
        ]
    ],
    "notes": "Default directory where plebbit-cli will keep its config: %LOCALAPPDATA%\\plebbit",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/plebbit/plebbit-cli/releases/download/v$version/plebbit_installer_win32_x64.exe#/dl.7z"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/mangayomi.json
{
    "version": "0.6.5",
    "description": "Free and open source application for reading manga, novels, and watching animes available on Android, iOS, macOS, Linux and Windows",
    "homepage": "https://github.com/kodjodevf/mangayomi",
    "license": "Apache-2.0",
    "url": "https://github.com/kodjodevf/mangayomi/releases/download/v0.6.5/Mangayomi-v0.6.5-windows.zip",
    "hash": "1fb2537137f7411a229a05fe5c989d4d7fd68c8c8fdc609d9ebe5cf88f0d577c",
    "shortcuts": [
        [
            "mangayomi.exe",
            "Mangayomi"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/kodjodevf/mangayomi/releases/download/v$version/Mangayomi-v$version-windows.zip"
    }
}

=== kkzzhizhou/scoop-apps/bucket/php5.2.2.json
{
 "bin": [
  "php.exe",
  "php-cgi.exe"
 ],
 "env_set": {
  "PHP_INI_SCAN_DIR": "$persist_dir;$dir\\conf.d;"
 },
 "hash": "fc3fa03e2824c09ccbc59a9b84b6d1d03e1ff29bd238206f25358ed75554e026",
 "homepage": "http://windows.php.net",
 "license": "http://www.php.net/license/3_01.txt",
 "persist": [
  "conf.d"
 ],
 "post_install": "iex(gc $bucketsdir\\$bucket\\bin\\postinstall.ps1 -Raw)",
 "url": "http://museum.php.net/php5/php-5.2.2-Win32.zip",
 "version": "5.2.2"
}

=== kkzzhizhou/scoop-apps/bucket/php5.6.15-nts_cmontage.json
{
  "homepage": "https://windows.php.net/downloads/releases/archives",
  "version": "5.6.15",
  "license": {
    "identifier": "PHP-3.01",
    "url": "https://www.php.net/license/"
  },
  "architecture": {
    "64bit": {
      "url": "https://windows.php.net/downloads/releases/archives/php-5.6.15-nts-Win32-VC11-x64.zip",
      "hash": "81fcb40baaec4d496aa300cdef62d3007af83b4d9a41e88f9eb545c61e3a115a"
    },
    "32bit": {
      "url": "https://windows.php.net/downloads/releases/archives/php-5.6.15-nts-Win32-VC11-x86.zip",
      "hash": "560c3ffd3a4bbe2679859e40ee4d7dbacfacb0c25e1ebc9f5be822412defbacc"
    }
  },
  "bin": [
    "php.exe",
    "php-cgi.exe"
  ],
  "persist": "conf.d",
  "env_set": {
    "PHP_INI_SCAN_DIR": "$persist_dir;$dir\\conf.d;"
  },
  "post_install": "if($bucket) { . \"$(Find-BucketDirectory $bucket\\bin\\postinstall.ps1)\" -dir \"$dir\" }",
  "suggest": {
    "vcredist": "extras/vcredist2012"
  }
}

=== kkzzhizhou/scoop-apps/bucket/good-mitm.json
{
    "version": "0.2.4",
    "description": "利用MITM技术实现请求和返回的重写、重定向、阻断等操作",
    "homepage": "https://github.com/zu1k/good-mitm",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/zu1k/good-mitm/releases/download/0.2.4/good-mitm-x86_64-pc-windows-gnu-0.2.4.zip",
            "hash": "81d0fac27f07270174da935af1f5a37cdc272a2e83f51d6de0f1c7fbad36c127"
        }
    },
    "extract_dir": "bin",
    "pre_install": "Get-ChildItem \"$dir\" 'good-mitm-*.exe' | Select-Object -First 1 | Rename-Item -NewName 'good-mitm.exe'",
    "bin": "good-mitm.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/zu1k/good-mitm/releases/download/$version/good-mitm-x86_64-pc-windows-gnu-$version.zip"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/sirikali-aoks.json
{
    "version": "1.8.5",
    "description": "A Qt/C++ GUI front end to sshfs, ecryptfs-simple, cryfs, gocryptfs, securefs, fscrypt and encfs.",
    "homepage": "https://mhogomchungu.github.io/sirikali/",
    "license": "GPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/mhogomchungu/sirikali/releases/download/1.8.5/SiriKaliQt6-1.8.5.zip",
            "hash": "18682c37204ef8e77006093019112ce84bb82b270775b57ddb6d3ac9cef2ef47"
        }
    },
    "##": "see installer options here - https://jrsoftware.org/ishelp/index.php?topic=setupcmdline",
    "bin": "sirikali.exe",
    "depends": "nonportable/sshfs-np",
    "checkver": {
        "github": "https://github.com/mhogomchungu/sirikali"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/mhogomchungu/sirikali/releases/download/$version/SiriKaliQt6-$version.zip"
            }
        }
    }
}
