=== kkzzhizhou/scoop-apps/bucket/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "A comment."
        },
        "_comment": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "identifier": {
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== kkzzhizhou/scoop-apps/bucket/shareenum_mo-san.json
{
    "homepage": "https://docs.microsoft.com/en-us/sysinternals/",
    "description": "Scan file shares on your network and view their security settings to close security holes.",
    "license": {
        "identifier": "Freeware",
        "url": "https://docs.microsoft.com/en-us/sysinternals/license-terms"
    },
    "version": "1.61",
    "url": "https://download.sysinternals.com/files/ShareEnum.zip",
    "hash": "7f88cabcf12a502e8242d5d1d899ee6d1ddec6642e56cbd6511a698827cbfcba",
    "checkver": {
        "url": "https://docs.microsoft.com/en-us/sysinternals/downloads/shareenum",
        "re": "ShareEnum\\s(?:v|V)?([\\d.]+)"
    },
    "autoupdate": {
        "url": "https://download.sysinternals.com/files/ShareEnum.zip"
    },
    "architecture": {
        "32bit": {
            "bin": "ShareEnum.exe",
            "shortcuts": [
                [
                    "ShareEnum.exe",
                    "SysInternals/ShareEnum",
                    "/accepteula"
                ]
            ]
        },
        "64bit": {
            "bin": "ShareEnum.exe",
            "shortcuts": [
                [
                    "ShareEnum.exe",
                    "SysInternals/ShareEnum",
                    "/accepteula"
                ]
            ]
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/WPS-CN.json
{
    "homepage": "https://platform.wps.cn",
    "description": "Complete office suite",
    "version": "12.1.0.19770",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.wps.com/eula"
    },
    "url": "https://official-package.wpscdn.cn/wps/download/WPS_Setup_19770.exe#/dl.7z",
    "hash": "ca6f0e5a83bd82deb914c54b8b813f5eed9f6725b4cb1a08cbedb080f1224cb9",
    "extract_dir": "$_11_",
    "pre_install": [
        "Expand-7zipArchive \"$dir\\`$EXEFILE\" -Switches '-t#'",
        "Remove-Item \"$dir\\*\" -Exclude '4.7z','2.7z' -Recurse",
        "Expand-7zipArchive \"$dir\\4.7z\" -ExtractDir 'office6' -Removal",
        "Expand-7zipArchive \"$dir\\2.7z\" -ExtractDir 'CONTROL\\office6' -Removal"
    ],
    "shortcuts": [
        [
            "wpsoffice.exe",
            "WPS Office"
        ],
        [
            "wps.exe",
            "WPS 文字"
        ],
        [
            "et.exe",
            "WPS 表格"
        ],
        [
            "wpp.exe",
            "WPS 演示"
        ],
        [
            "ksomisc.exe",
            "WPS 配置工具"
        ]
    ],
    "checkver": "WPS_Setup_(?<num>\\d+).exe",
    "autoupdate": {
        "url": "https://official-pacakge.wpscdn.cn/wps/download/WPS_Setup_$matchNum.exe#/dl.7z",
        "extract_dir": "$_$majorVersion_"
    }
}

=== kkzzhizhou/scoop-apps/bucket/FixPrintSpooler.json
{
    "version": "1.2",
    "description": "Sordum's Fix Print Spooler. Fix casual problems with print spooler service.",
    "homepage": "https://www.sordum.org/9199/",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.sordum.org/eula/"
    },
    "url": "https://www.sordum.org/files/small-tools/FixPrintSpooler.zip",
    "hash": "b6f8fc83c8c22febca0e1429a360911a45a135d29737a6e8449edaf4a3708bdb",
    "extract_dir": "FixPrintSpooler_v1.2",
    "architecture": {
        "64bit": {
            "bin": [
                "FixSpooler_x64.exe",
                [
                    "FixSpooler_x64.exe",
                    "FixSpooler"
                ]
            ],
            "shortcuts": [
                [
                    "FixSpooler_x64.exe",
                    "Sordum\\Fix Print Spooler"
                ]
            ]
        },
        "32bit": {
            "bin": "FixSpooler.exe",
            "shortcuts": [
                [
                    "FixSpooler.exe",
                    "Sordum\\Fix Print Spooler"
                ]
            ]
        }
    },
    "checkver": "v([\\d.]+)",
    "autoupdate": {
        "url": "https://www.sordum.org/files/small-tools/FixPrintSpooler.zip",
        "extract_dir": "FixPrintSpooler_v$version"
    }
}

=== kkzzhizhou/scoop-apps/bucket/clawpdf-np.json
{
    "version": "0.9.3",
    "homepage": "https://github.com/clawsoftware/clawPDF",
    "description": "An opens Source Virtual (Network) Printer for Windows that allows you to create PDFs, OCR text, and print images",
    "license": "AGPL-3.0",
    "notes": "You may have to restart your system after installing/uninstalling clawPDF for it to function properly.",
    "url": "https://github.com/clawsoftware/clawPDF/releases/download/0.9.3/clawPDF_0.9.3_setup.msi#/setup.msi_",
    "hash": "4b8102955e7a75149c45efc968643db87b3aed85753136b186734ee1c614298c",
    "installer": {
        "script": [
            "if (!(is_admin)) { error \"$app requires admin rights to $cmd\"; break }",
            "$dateName = (Get-Date).ToString('yyyy.MM.dd_HH.mm.ss.ffffff')",
            "Start-Process 'msiexec' -Wait -Verb 'RunAs' -Args @('/i', \"$dir\\setup.msi_\", '/qn', '/norestart', '/log', \"$dir\\clawPDF_install_$dateName.log\")",
            "[System.IO.File]::WriteAllLines(\"$dir\\clawpdf.cmd\", '@\"%ProgramFiles(x86)%\\clawPDF\\clawPDF.exe\"  %*', [System.text.UTF8Encoding]($false))",
            "[System.IO.File]::WriteAllLines(\"$dir\\setuphelper.cmd\", '@\"%ProgramFiles(x86)%\\clawPDF\\SetupHelper.exe\"  %*', [System.text.UTF8Encoding]($false))",
            "[System.IO.File]::WriteAllLines(\"$dir\\clawpdf.bridge.cmd\", '@\"%ProgramFiles(x86)%\\clawPDF\\clawPDF.Bridge.exe\"  %*', [System.text.UTF8Encoding]($false))"
        ]
    },
    "uninstaller": {
        "script": [
            "if (!(is_admin)) { error \"$app requires admin rights to $cmd\"; break }",
            "$dateName = (Get-Date).ToString('yyyy.MM.dd_HH.mm.ss.ffffff')",
            "Start-Process 'msiexec' -Wait -Verb 'RunAs' -Args @('/x', \"$dir\\setup.msi_\", '/qn', '/norestart', '/log', \"$dir\\clawPDF_uninstall_$dateName.log\")",
            "Get-ChildItem \"$dir\\*.log\" | Move-Item -Destination \"$persist_dir\\MSI_Logs\"",
            "warn 'You may have to restart your system after uninstalling clawPDF to completely remove the virtual printer.'"
        ]
    },
    "bin": [
        "clawpdf.cmd",
        "setuphelper.cmd",
        "clawpdf.bridge.cmd"
    ],
    "persist": "MSI_Logs",
    "post_install": "Get-ChildItem \"$dir\\*.log\" | Move-Item -Destination \"$persist_dir\\MSI_Logs\"",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/clawsoftware/clawPDF/releases/download/$version/clawPDF_$version_setup.msi#/setup.msi_"
    }
}

=== kkzzhizhou/scoop-apps/bucket/scoop-backup-KNOXDEV_hu3rror.json
{
    "homepage": "https://git.irs.sh/KNOXDEV",
    "description": "Additional backup functionality for the Scoop Package Manager",
    "license": "Unlicense",
    "version": "0.2022.01.05",
    "url": "https://github.com/hu3rror/scoop-backup/archive/667c0b3bd0644a4955b6ccc6089a028faf9c12ba.zip",
    "hash": "d92ccab39b2b929ae49dab77d8e0d8394459b3b881d8187d50f13da64e8a165a",
    "extract_dir": "scoop-backup-667c0b3bd0644a4955b6ccc6089a028faf9c12ba",
    "bin": "scoop-backup.ps1",
    "persist": "backups"
}

=== kkzzhizhou/scoop-apps/bucket/blackbox_exporter.json
{
    "version": "0.21.1",
    "description": "A Prometheus exporter allows blackbox probing of endpoints over HTTP, HTTPS, DNS, TCP and ICMP.",
    "homepage": "https://github.com/prometheus/blackbox_exporter",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/prometheus/blackbox_exporter/releases/download/v0.21.1/blackbox_exporter-0.21.1.windows-amd64.tar.gz",
            "hash": "880c5d274705b063053ae2eb6b9449aa68b554f05687edfc1663eca18961b1f0",
            "extract_dir": "blackbox_exporter-0.21.1.windows-amd64"
        },
        "32bit": {
            "url": "https://github.com/prometheus/blackbox_exporter/releases/download/v0.21.1/blackbox_exporter-0.21.1.windows-386.tar.gz",
            "hash": "b527406701de94cd8c8731d8b1ba8616bf864f48ccb1927d23243b525b5acb2b",
            "extract_dir": "blackbox_exporter-0.21.1.windows-386"
        }
    },
    "persist": "blackbox.yml",
    "bin": "blackbox_exporter.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/prometheus/blackbox_exporter/releases/download/v$version/blackbox_exporter-$version.windows-amd64.tar.gz",
                "extract_dir": "blackbox_exporter-$version.windows-amd64"
            },
            "32bit": {
                "url": "https://github.com/prometheus/blackbox_exporter/releases/download/v$version/blackbox_exporter-$version.windows-386.tar.gz",
                "extract_dir": "blackbox_exporter-$version.windows-386"
            }
        },
        "hash": {
            "url": "$baseurl/sha256sums.txt"
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/wu10man.json
{
    "homepage": "https://github.com/WereDev/Wu10Man",
    "version": "4.4.0",
    "license": "GPL-3.0-only",
    "url": "https://github.com/WereDev/Wu10Man/releases/download/v4.4.0/Wu10Man_Portable.zip",
    "hash": "58d0ae4eac8841b04f4c553fc80d4ecd80a89b9a7ff3481250ac2653cdb6aa17",
    "shortcuts": [
        [
            "Wu10Man.exe",
            "Wu10Man"
        ]
    ],
    "checkver": {
        "github": "https://github.com/WereDev/Wu10Man"
    },
    "autoupdate": {
        "url": "https://github.com/WereDev/Wu10Man/releases/download/v$version/Wu10Man_Portable.zip"
    }
}

=== kkzzhizhou/scoop-apps/bucket/pdm.json
{
    "homepage": "http://pdm-project.org",
    "version": "2.26.0",
    "description": "Python package and dependency manager supporting the latest PEP standards",
    "license": "MIT",
    "url": "https://files.pythonhosted.org/packages/7b/32/98de42122e114f131d17d872adb68870f15a165a1d873aa7b7690ea53951/pdm-2.26.0-py3-none-any.whl",
    "depends": "python",
    "hash": "ed164843f1849148a5c66073b29028a701205465484e3f0a7066016b42d5e3fb",
    "bin": "venv\\Scripts\\pdm.exe",
    "installer": {
        "script": [
            "python -m venv \"$dir\\venv\"",
            "& \"$dir\\venv\\Scripts\\python.exe\" -m pip install \"$dir\\$fname\""
        ]
    },
    "post_install": [
        "if (-not (Test-Path -Path $PROFILE\\..\\Completions -PathType Container)) {",
        "    mkdir $PROFILE\\..\\Completions",
        "    echo @'",
        "Get-ChildItem \"$PROFILE\\..\\Completions\\\" | ForEach-Object {",
        "    . $_.FullName",
        "}",
        "'@ | Out-File -Append -Encoding utf8 $PROFILE",
        "}",
        "& \"$dir\\venv\\Scripts\\pdm.exe\" completion powershell | Out-File -Encoding utf8 $PROFILE\\..\\Completions\\pdm_completion.ps1"
    ],
    "uninstaller": {
        "script": [
            "$oldPath = [Environment]::GetEnvironmentVariable(\"PYTHONPATH\", [System.EnvironmentVariableTarget]::User)",
            "If (-not [string]::IsNullOrWhiteSpace($oldPath)) {",
            "    $newPath = ($oldPath.Split(';') | Where { $_ -notlike \"$dir\\venv\\*\" }) -join ';'",
            "    [Environment]::SetEnvironmentVariable(\"PYTHONPATH\", $newPath, [System.EnvironmentVariableTarget]::User)",
            "}",
            "Remove-Item -Path $PROFILE\\..\\Completions\\pdm_completion.ps1 -ErrorAction SilentlyContinue"
        ]
    },
    "checkver": {
        "url": "https://pypi.org/pypi/pdm/json",
        "jp": "$.urls[?(@.packagetype == 'bdist_wheel')].url",
        "re": "https://files.pythonhosted.org/packages/(.*/pdm-(?<version>[\\d.]+(?:post\\d+)?)-.*\\.whl)",
        "replace": "${version}"
    },
    "autoupdate": {
        "url": "https://files.pythonhosted.org/packages/$match1"
    }
}
